### ISSUE TITLE
No error on "Save playlist" without entering a Name

### ISSUE THREAD

**Issue by dwaq** [loverajoel/magicplaylist#3]
After entering a song and clicking "Save playlist on Spotify", the next screen has a blank space for Name. Attempting to click "Save playlist" without first entering a Name doesn't cause an error message or do anything. 

I suggest adding an error message if you attempt to save without a Name entered.

I also suggest auto-filling the Name of the playlist with the song title that was entered to start this whole process.

I can attempt to fix this issue myself, but don't have much experience with this stack.

**Comment by loverajoel** [comment]
Hi @dwaq thanks for your help!
Here is the pr https://github.com/loverajoel/magicplaylist/pull/10
