### ISSUE TITLE
Dropdown with options gets behind footer text when one or more songs have two line titles

### ISSUE THREAD

**Issue by PabloVerano** [loverajoel/magicplaylist#4]
Last item on the list becomes unclickable.
Screenshot: Chrome 46, 1366x768, Win 8.

![image](https://cloud.githubusercontent.com/assets/3749900/10845071/a4aba994-7ee3-11e5-9795-f7a9fffdea8e.png)

**Comment by loverajoel** [comment]
ok, I will take a look, thanks

**Comment by loverajoel** [comment]
Thanks here the pr https://github.com/loverajoel/magicplaylist/pull/11
