### ISSUE TITLE
Prevent 30s audio preview prefetching

### ISSUE THREAD

**Issue by JMPerez** [loverajoel/magicplaylist#7]
When searching for a song, the results trigger requests for downloading the 30s previews. This is due to having an `<audio />` tag per result.

Even though it seems a good idea, it results in lots of data being downloaded and unlikely to be needed. This can be problematic when used from mobile devices (it's 30 results and each result downloads a ~355kB file).

A better approach would be to create a single Audio javascript object, and assign its `src` when a user wants to play something, similar to [this example](https://github.com/JMPerez/thirtiflux/blob/master/app/components/album-tracks.jsx#L44).

**Comment by loverajoel** [comment]
Awesome approach, I know that Safari for ios don't preload the audio files until you force to play, that's the reason for I didn't care about it.
But I don't know how Android works, I will evaluate your approach and try apply.
I will back to you with the PR.
Thanks

**Comment by loverajoel** [comment]
I decided use the property `preload='none'` in order to prevent load all files. Here is the PR https://github.com/loverajoel/magicplaylist/pull/14 .
Thanks
