### ISSUE TITLE
Unnecessary user-read-private scope

### ISSUE THREAD

**Issue by JMPerez** [loverajoel/magicplaylist#8]
Browsing the code it doesn't seem that the `user-read-private` scope is needed. Neither user's account country nor product are being used in the code.

**Comment by loverajoel** [comment]
@JMPerez I'm showing the `display_name` in the save modal and I saw in the [API Doc](https://developer.spotify.com/web-api/get-current-users-profile/) that appears as `user object (private)`.
Now that you mention it, I will review and delete. Thanks

**Comment by JMPerez** [comment]
@loverajoel the `display_name` is part of the public information that you get without providing additional scopes, so there is no need to include `user-read-private` as part of the requested scopes.

**Comment by loverajoel** [comment]
PR https://github.com/loverajoel/magicplaylist/pull/9
